version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    version-update: semver-major
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      docusaurus:
        patterns:
          - '@docusaurus*'
          - 'docusaurus*'
      production-dependencies:
        dependency-type: 'production'
        exclude-patterns:
          - '@docusaurus*'
          - 'docusaurus*'
      development-dependencies:
        dependency-type: 'development'
        exclude-patterns:
          - '@docusaurus*'
          - 'docusaurus*'
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
    groups:
      submodules:
        patterns:
          - '*'
    open-pull-requests-limit: 1
