import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  theoplayer: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'category',
      label: 'API references',
      link: { type: 'generated-index', slug: 'api' },
      items: [
        {
          type: 'link',
          label: 'Web',
          href: 'pathname:///theoplayer/v6/api-reference/web/',
        },
        {
          type: 'link',
          label: 'Android',
          href: 'pathname:///theoplayer/v6/api-reference/android/',
        },
        {
          type: 'link',
          label: 'iOS',
          href: 'pathname:///theoplayer/v6/api-reference/ios/',
        },
      ],
    },
  ],
};

export default sidebars;
