import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  theolive: [
    'index',
    'introduction-backend',
    'introduction-player',
    {
      type: 'category',
      label: 'Guides',
      customProps: {
        icon: '🚀',
      },
      description: 'THEOLive guides',
      link: { type: 'doc', id: 'guides/authorization' },
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    'troubleshooting',
  ],
};

export default sidebars;
