import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import signalingApiSidebar from './ads/api/signaling/sidebar';

const sidebars: SidebarsConfig = {
  ads: [
    'index',
    {
      type: 'category',
      label: 'Core concepts',
      description: 'Understand the resources that power OptiView Ads.',
      collapsed: false,
      customProps: {
        icon: '📚',
      },
      items: [
        'concepts/channels',
        'concepts/breaks',
        'concepts/templates',
        'concepts/events',
        'concepts/origins',
        'concepts/marker-detection',
        'concepts/break-manifest',
      ],
    },
    {
      type: 'category',
      label: 'Vendors',
      description: 'Configure vendor integrations for server-guided and server-side ad insertion.',
      customProps: {
        icon: '🏷️',
      },
      link: { type: 'doc', id: 'vendors/index' },
      items: ['vendors/google'],
    },
    {
      type: 'category',
      label: 'Getting started',
      description: 'Set up your first stream with OptiView Ads!',
      collapsed: false,
      customProps: {
        icon: '🚀',
      },
      link: { type: 'doc', id: 'getting-started/index' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Player integration',
      description: 'Connect OptiView Ads to a player.',
      collapsed: false,
      customProps: {
        icon: '▶️',
      },
      link: { type: 'doc', id: 'player-integration/index' },
      items: [
        {
          type: 'category',
          label: 'OptiView Player',
          customProps: { icon: '🎬' },
          link: { type: 'doc', id: 'player-integration/optiview-player/index' },
          items: [
            'player-integration/optiview-player/web',
            'player-integration/optiview-player/android',
            'player-integration/optiview-player/ios',
            'player-integration/optiview-player/chromecast',
            'player-integration/optiview-player/react-native',
            {
              type: 'link',
              label: 'Web TheoAdDescription API',
              href: 'https://optiview.dolby.com/docs/theoplayer/v11/api-reference/web/interfaces/TheoAdDescription.html',
            },
            {
              type: 'link',
              label: 'Android TheoAdDescription API',
              href: 'https://optiview.dolby.com/docs/theoplayer/v11/api-reference/android/com/theoplayer/android/api/ads/theoads/TheoAdDescription.html',
            },
            {
              type: 'link',
              label: 'iOS THEOAdDescription API',
              href: 'https://optiview.dolby.com/docs/theoplayer/v11/api-reference/ios/Structs/THEOAdDescription.html',
            },
            {
              type: 'link',
              label: 'React Native TheoAdDescription API',
              href: 'https://theoplayer.github.io/react-native-theoplayer/api/interfaces/TheoAdDescription.html',
            },
          ],
        },
        {
          type: 'category',
          label: 'Bring your own player',
          customProps: { icon: '🧩' },
          link: { type: 'doc', id: 'player-integration/bring-your-own-player/index' },
          items: [
            'player-integration/bring-your-own-player/hls-js',
            'player-integration/bring-your-own-player/shaka-player',
            'player-integration/bring-your-own-player/exoplayer-media3',
            'player-integration/bring-your-own-player/avplayer',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'How-to guides',
      description: 'Learn how to integrate OptiView Ads with your setup',
      customProps: {
        icon: '📖',
      },
      link: { type: 'doc', id: 'how-to-guides/index' },
      items: [{ type: 'autogenerated', dirName: 'how-to-guides' }],
    },
    {
      type: 'category',
      label: 'Limitations and known issues',
      description: 'Take notice of the limitations and known issues when using OptiView Ads.',
      customProps: {
        icon: '⚠️',
      },
      link: { type: 'doc', id: 'limitations/index' },
      items: [{ type: 'autogenerated', dirName: 'limitations' }],
    },
    {
      type: 'category',
      label: 'API references',
      description: 'Discover all functions of OptiView Ads.',
      customProps: {
        icon: '*️⃣',
      },
      link: { type: 'generated-index', slug: 'api' },
      items: [
        {
          type: 'link',
          label: 'Signaling Service',
          customProps: { icon: '🛜' },
          href: '/ads/api/signaling/theoads-api',
        },
        {
          type: 'link',
          label: 'Web',
          customProps: { icon: 'web' },
          href: 'https://optiview.dolby.com/docs/theoplayer/v11/api-reference/web/interfaces/TheoAdDescription.html',
        },
      ],
    },
  ],
  signalingApi: [
    {
      type: 'link',
      label: '« Back',
      href: '/ads/',
    },
    ...signalingApiSidebar,
  ],
};

export default sidebars;
