import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import type { SidebarItemConfig, SidebarItem, SidebarItemDoc, SidebarItemCategory } from '@docusaurus/plugin-content-docs/lib/sidebars/types.d.ts';
import millicastApiSidebar from './millicast/api/sidebar';
import millicastAdvancedReportingApiSidebar from './millicast/api/reporting/sidebar';
import millicastDirectorApiSidebar from './millicast/api/director/sidebar';

function isCategory(item: SidebarItemConfig): item is SidebarItemCategory {
  return (item as SidebarItemCategory).type === 'category';
}

function isDoc(item: SidebarItem): item is SidebarItemDoc {
  return item.type === 'doc';
}

function isHiddenCategory(item: SidebarItemConfig): item is SidebarItemCategory {
  return isCategory(item) && item.label === 'hidden';
}

function removeHiddenItems(data: SidebarItemConfig[]): SidebarItemConfig[] {
  // find the "hidden" category and get its item IDs
  const hiddenCategory = data.find(isHiddenCategory);
  const hiddenIds = new Set(hiddenCategory?.items.filter(isDoc).map((item) => item.id) ?? []);

  // filter out items from other categories that match the hidden IDs
  const updatedData = data
    .map((category) => {
      if (isCategory(category)) {
        // filter out the items that match any of the hidden IDs
        const filteredItems = category.items.filter((item) => !(isDoc(item) && hiddenIds.has(item.id)));

        // if all items are removed, omit the category entirely
        if (filteredItems.length === 0) {
          // remove the category
          return null;
        }

        // return the category with filtered items
        return { ...category, items: filteredItems };
      }
      return category;
    })
    // Remove null categories
    .filter((category) => category !== null);

  return updatedData;
}

// filter "hidden" items
const filteredMillicastApiSidebar = removeHiddenItems(millicastApiSidebar);
const filteredMillicastAdvancedReportingApiSidebar = removeHiddenItems(millicastAdvancedReportingApiSidebar);
const filteredMillicastDirectorApiSidebar = removeHiddenItems(millicastDirectorApiSidebar);

const sidebars: SidebarsConfig = {
  millicast: [
    'introduction-to-streaming-apis',
    {
      type: 'category',
      label: 'Getting started',
      customProps: {
        icon: '🚀',
      },
      description: 'Getting started with Millicast',
      link: { type: 'doc', id: 'getting-started/index' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Streaming guides',
      customProps: {
        icon: '📖',
      },
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Capture',
          customProps: {
            icon: '🎥',
          },
          link: { type: 'doc', id: 'capture/index' },
          items: [{ type: 'autogenerated', dirName: 'capture' }],
        },
        {
          type: 'category',
          label: 'Broadcast',
          customProps: {
            icon: '📡',
          },
          link: { type: 'doc', id: 'broadcast/index' },
          items: [{ type: 'autogenerated', dirName: 'broadcast' }],
        },
        {
          type: 'category',
          label: 'Distribution',
          customProps: {
            icon: '🚚',
          },
          link: { type: 'doc', id: 'distribution/index' },
          items: [{ type: 'autogenerated', dirName: 'distribution' }],
        },
        {
          type: 'category',
          label: 'Playback',
          customProps: {
            icon: '▶️',
          },
          link: { type: 'doc', id: 'playback/index' },
          items: [{ type: 'autogenerated', dirName: 'playback' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Platform guides',
      customProps: {
        icon: '📖',
      },
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Platform Requirements',
          customProps: {
            icon: '✅',
          },
          link: { type: 'doc', id: 'platform-requirements/index' },
          items: [{ type: 'autogenerated', dirName: 'platform-requirements' }],
        },
        {
          type: 'category',
          label: 'Streaming Dashboard',
          customProps: {
            icon: '📡',
          },
          link: { type: 'doc', id: 'streaming-dashboard/index' },
          items: [{ type: 'autogenerated', dirName: 'streaming-dashboard' }],
        },
        {
          type: 'category',
          label: 'Analytics',
          customProps: {
            icon: '📊',
          },
          link: { type: 'doc', id: 'analytics/index' },
          items: [{ type: 'autogenerated', dirName: 'analytics' }],
        },
        {
          type: 'category',
          label: 'Webhooks',
          customProps: {
            icon: '🪝',
          },
          link: { type: 'doc', id: 'webhooks/index' },
          items: [{ type: 'autogenerated', dirName: 'webhooks' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'SDKs and tools',
      customProps: {
        icon: '🔧',
      },
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Client SDKs',
          customProps: {
            icon: '▶️',
          },
          link: { type: 'doc', id: 'client-sdks/index' },
          items: [
            'client-sdks/web',
            {
              type: 'category',
              label: 'Android',
              customProps: {
                icon: 'android',
              },
              link: { type: 'doc', id: 'client-sdks/android/index' },
              items: [{ type: 'autogenerated', dirName: 'client-sdks/android' }],
            },
            {
              type: 'category',
              label: 'iOS',
              customProps: {
                icon: 'apple',
              },
              link: { type: 'doc', id: 'client-sdks/ios/index' },
              items: [{ type: 'autogenerated', dirName: 'client-sdks/ios' }],
            },
            'client-sdks/rn',
            'client-sdks/flutter',
            {
              type: 'category',
              label: 'Desktop',
              customProps: {
                icon: '🖥️',
              },
              link: { type: 'doc', id: 'client-sdks/desktop/index' },
              items: [{ type: 'autogenerated', dirName: 'client-sdks/desktop' }],
            },
          ],
        },
        {
          type: 'category',
          label: 'Sample Apps',
          customProps: {
            icon: '🛝',
          },
          link: { type: 'doc', id: 'sample-apps/index' },
          items: [{ type: 'autogenerated', dirName: 'sample-apps' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      customProps: {
        icon: '🔌',
      },
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Client Analytics',
          customProps: {
            icon: '📊',
          },
          link: { type: 'doc', id: 'client-analytics/index' },
          items: [{ type: 'autogenerated', dirName: 'client-analytics' }],
        },
        {
          type: 'category',
          label: 'Hardware Encoders',
          customProps: {
            icon: '🖥️',
          },
          items: [{ type: 'autogenerated', dirName: 'hardware-encoders' }],
        },
        {
          type: 'category',
          label: 'Software Encoders',
          customProps: {
            icon: '💿',
          },
          items: [{ type: 'autogenerated', dirName: 'software-encoders' }],
        },
        // TODO Port https://docs.dolby.io/streaming-apis/docs/amino
        // {
        //   type: 'category',
        //   label: 'Playback Devices',
        //   customProps: {
        //     icon: '📺',
        //   },
        //   items: ['amino'],
        // },
      ],
    },
    {
      type: 'link',
      label: 'Millicast REST API',
      customProps: {
        icon: '🛜',
      },
      href: '/millicast/api/millicast-api',
    },
    {
      type: 'link',
      label: 'Release Notes',
      customProps: {
        icon: '📝',
      },
      href: '/millicast/changelog/',
    },
  ],
  millicastReleaseNotes: [
    {
      type: 'link',
      label: '« Back',
      href: '/millicast/',
    },
    {
      type: 'category',
      label: 'Release Notes',
      customProps: {
        icon: '📝',
      },
      link: { type: 'doc', id: 'changelog' },
      items: [
        {
          type: 'doc',
          label: 'Platform and Media Server',
          id: 'changelog/changelog-dolbyio-platform-media-server',
        },
        {
          type: 'doc',
          label: 'REST APIs Changes',
          id: 'changelog/changelog-rest-apis',
        },
        {
          type: 'doc',
          label: 'Dashboard Changes',
          id: 'changelog/changelog-dolbyio-dashboard',
        },
        {
          type: 'doc',
          label: 'Native SDK',
          id: 'changelog/changelog-native-sdk',
        },
        {
          type: 'doc',
          label: 'Web SDK',
          id: 'changelog/changelog-web-platform',
        },
        {
          type: 'doc',
          label: 'OBS WebRTC',
          id: 'changelog/changelog-obs-webrtc',
        },
      ],
    },
  ],
  millicastApi: [
    {
      type: 'link',
      label: '« Back',
      href: '/millicast/',
    },
    {
      type: 'category',
      label: 'Millicast API',
      collapsible: true,
      collapsed: false,
      items: [...filteredMillicastApiSidebar],
    },
    {
      type: 'category',
      label: 'Millicast Advanced Reporting API',
      collapsible: true,
      collapsed: true,
      items: [...filteredMillicastAdvancedReportingApiSidebar],
    },
    {
      type: 'category',
      label: 'Millicast Director API',
      collapsible: true,
      collapsed: true,
      items: [...filteredMillicastDirectorApiSidebar],
    },
  ],
};

export default sidebars;
