import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import signalingApiSidebar from './ads/api/signaling/sidebar';

const sidebars: SidebarsConfig = {
  ads: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      description: 'Set up your first stream with OptiView Ads!',
      collapsed: false,
      customProps: {
        icon: '🚀',
      },
      link: { type: 'doc', id: 'getting-started/index' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Player integration',
      description: 'Connect OptiView Ads to a player.',
      collapsed: false,
      customProps: {
        icon: '▶️',
      },
      link: { type: 'doc', id: 'player-integration/index' },
      items: [
        {
          type: 'category',
          label: 'OptiView Ads SDK',
          customProps: { icon: '🧩' },
          link: { type: 'doc', id: 'player-integration/optiview-ads-sdk/index' },
          items: [
            'player-integration/optiview-ads-sdk/web',
            'player-integration/optiview-ads-sdk/android',
            'player-integration/optiview-ads-sdk/ios',
            'player-integration/optiview-ads-sdk/react-native',
          ],
        },
        {
          type: 'category',
          label: 'OptiView Player',
          customProps: { icon: '🎬' },
          link: { type: 'doc', id: 'player-integration/optiview-player/index' },
          items: [
            'player-integration/optiview-player/web',
            'player-integration/optiview-player/android',
            'player-integration/optiview-player/ios',
            'player-integration/optiview-player/react-native',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Core concepts',
      description: 'Understand the resources that power OptiView Ads.',
      collapsed: false,
      customProps: {
        icon: '📚',
      },
      items: [{ type: 'autogenerated', dirName: 'concepts' }],
    },
    {
      type: 'category',
      label: 'Integrations',
      description: 'Configure integrations for server-guided and server-side ad insertion.',
      customProps: {
        icon: '🏷️',
      },
      link: { type: 'doc', id: 'integrations/index' },
      items: [{ type: 'autogenerated', dirName: 'integrations' }],
    },
    {
      type: 'category',
      label: 'How-to guides',
      description: 'Learn how to integrate OptiView Ads with your setup',
      customProps: {
        icon: '📖',
      },
      link: { type: 'doc', id: 'how-to-guides/index' },
      items: [{ type: 'autogenerated', dirName: 'how-to-guides' }],
    },
    {
      type: 'category',
      label: 'Limitations and known issues',
      description: 'Take notice of the limitations and known issues when using OptiView Ads.',
      customProps: {
        icon: '⚠️',
      },
      link: { type: 'doc', id: 'limitations/index' },
      items: [{ type: 'autogenerated', dirName: 'limitations' }],
    },
    {
      type: 'category',
      label: 'API references',
      description: 'Discover all functions of OptiView Ads.',
      customProps: {
        icon: '*️⃣',
      },
      link: { type: 'generated-index', slug: 'api' },
      items: [
        {
          type: 'link',
          label: 'Signaling Service',
          customProps: { icon: '🛜' },
          href: '/ads/api/signaling/theoads-api',
        },
        {
          type: 'link',
          label: 'Web',
          customProps: { icon: 'web' },
          href: 'https://optiview.dolby.com/docs/theoplayer/v11/api-reference/web/interfaces/TheoAdDescription.html',
        },
      ],
    },
  ],
  signalingApi: [
    {
      type: 'link',
      label: '« Back',
      href: '/ads/',
    },
    ...signalingApiSidebar,
  ],
};

export default sidebars;
