import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  web: [
    'web/index',
    { type: 'doc', id: 'getting-started/getting-started' },
    {
      type: 'category',
      label: 'How-to guides',
      description: 'Learn how to integrate THEOads with your setup',
      customProps: {
        icon: '📖',
      },
      link: { type: 'doc', id: 'how-to-guides/index' },
      items: [{ type: 'autogenerated', dirName: 'how-to-guides' }],
    }
  ]
};

export default sidebars;
