import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import apiSidebar from './adengine/reference/sidebar';

const sidebars: SidebarsConfig = {
  adengine: [
    'index',
    {
      type: 'category',
      label: 'How to',
      description: 'How to use OptiView Ad Engine',
      collapsed: false,
      customProps: {
        icon: '📖',
      },
      items: [{ type: 'autogenerated', dirName: 'how-to' }],
    },
    apiSidebar,
  ],
};

export default sidebars;
