import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  theoads: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      description: 'Set up your first stream with THEOads!',
      customProps: {
        icon: '🚀',
      },
      link: { type: 'doc', id: 'getting-started/index' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'How-to guides',
      description: 'Learn how to integrate THEOads with your setup',
      customProps: {
        icon: '📖',
      },
      link: { type: 'doc', id: 'how-to-guides/index' },
      items: [{ type: 'autogenerated', dirName: 'how-to-guides' }],
    },
    {
      type: 'category',
      label: 'Knowledge base',
      description: 'Learn more about THEOads from our experts.',
      customProps: {
        icon: '🧠',
      },
      link: { type: 'doc', id: 'knowledge-base/index' },
      items: [{ type: 'autogenerated', dirName: 'knowledge-base' }],
    },
    {
      type: 'category',
      label: 'API references',
      description: 'Discover all functions of THEOads.',
      customProps: {
        icon: '*️⃣',
      },
      items: [
        {
          type: 'link',
          label: 'OpenAPI',
          customProps: { icon: '🛜' },
          href: '/theoads/api/',
        },
      ],
    },
  ],
};

export default sidebars;
