import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import type { SidebarItem, SidebarItemCategory, SidebarItemConfig, SidebarItemDoc } from '@docusaurus/plugin-content-docs/lib/sidebars/types.d.ts';
import apiSidebar from './adengine/reference/sidebar';

function isCategory(item: SidebarItemConfig): item is SidebarItemCategory {
  return (item as SidebarItem).type === 'category';
}

function isDoc(item: SidebarItemConfig): item is SidebarItemDoc {
  return (item as SidebarItem).type === 'doc';
}

function cleanItems(data: SidebarItemConfig[]): SidebarItemConfig[] {
  return data
    .map((item) => {
      // Remove the auto generated Introduction from the REST APIs
      if (isDoc(item) && item.id === 'reference/dolby-optiview-ad-engine') {
        return null;
      }

      // Rename the REST APIs title
      if (isCategory(item) && item.label === 'Ad Engine') {
        item.label = 'REST APIs';
      }

      return item;
    })
    .filter((item) => {
      // Remove null items
      return item !== null;
    });
}

const sidebarItems: SidebarItemConfig[] = cleanItems(apiSidebar);

const sidebars: SidebarsConfig = {
  adengine: [
    'index',
    {
      type: 'category',
      label: 'How to',
      description: 'How to use OptiView Ad Engine',
      collapsed: false,
      collapsible: false,
      customProps: {
        icon: '📖',
      },
      items: [{ type: 'autogenerated', dirName: 'how-to' }],
    },
    ...sidebarItems,
  ],
};

export default sidebars;
