import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  millicast: [
    'index',
    {
      type: 'category',
      label: 'Tutorials',
      customProps: {
        icon: '🎓',
      },
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Getting started',
          customProps: {
            icon: '🚀',
          },
          description: 'Getting started with Millicast',
          link: { type: 'doc', id: 'getting-started/getting-started' },
          items: [{ type: 'autogenerated', dirName: 'getting-started' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Streaming guides',
      customProps: {
        icon: '📖',
      },
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Capture',
          customProps: {
            icon: '🎥',
          },
          link: { type: 'doc', id: 'capture/capture' },
          items: [{ type: 'autogenerated', dirName: 'capture' }],
        },
        {
          type: 'category',
          label: 'Broadcast',
          customProps: {
            icon: '📡',
          },
          link: { type: 'doc', id: 'broadcast/broadcast' },
          items: [{ type: 'autogenerated', dirName: 'broadcast' }],
        },
        {
          type: 'category',
          label: 'Distribution',
          customProps: {
            icon: '🚚',
          },
          link: { type: 'doc', id: 'distribution/distribution' },
          items: [{ type: 'autogenerated', dirName: 'distribution' }],
        },
        {
          type: 'category',
          label: 'Playback',
          customProps: {
            icon: '▶️',
          },
          link: { type: 'doc', id: 'playback/playback' },
          items: [{ type: 'autogenerated', dirName: 'playback' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Platform guides',
      customProps: {
        icon: '📖',
      },
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Platform Requirements',
          customProps: {
            icon: '✅',
          },
          link: { type: 'doc', id: 'platform-requirements/network-requirements' },
          items: [{ type: 'autogenerated', dirName: 'platform-requirements' }],
        },
        {
          type: 'category',
          label: 'Streaming Dashboard',
          customProps: {
            icon: '📡',
          },
          link: { type: 'doc', id: 'streaming-dashboard/about-dash' },
          items: [{ type: 'autogenerated', dirName: 'streaming-dashboard' }],
        },
        {
          type: 'category',
          label: 'Analytics',
          customProps: {
            icon: '📊',
          },
          link: { type: 'doc', id: 'analytics/analytics-api' },
          items: [{ type: 'autogenerated', dirName: 'analytics' }],
        },
        {
          type: 'category',
          label: 'Webhooks',
          customProps: {
            icon: '🪝',
          },
          link: { type: 'doc', id: 'webhooks/webhooks' },
          items: [{ type: 'autogenerated', dirName: 'webhooks' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'SDKs and tools',
      customProps: {
        icon: '🔧',
      },
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Client SDKs',
          customProps: {
            icon: '▶️',
          },
          link: { type: 'doc', id: 'client-sdks/client-sdks' },
          items: [
            'client-sdks/web',
            {
              type: 'category',
              label: 'Android',
              customProps: {
                icon: 'android',
              },
              link: { type: 'doc', id: 'client-sdks/android/android' },
              items: [{ type: 'autogenerated', dirName: 'client-sdks/android' }],
            },
            {
              type: 'category',
              label: 'iOS',
              customProps: {
                icon: 'apple',
              },
              link: { type: 'doc', id: 'client-sdks/ios/ios' },
              items: [{ type: 'autogenerated', dirName: 'client-sdks/ios' }],
            },
            'client-sdks/rn',
            'client-sdks/flutter',
            {
              type: 'category',
              label: 'Desktop',
              customProps: {
                icon: '🖥️',
              },
              link: { type: 'doc', id: 'client-sdks/desktop/desktop' },
              items: [{ type: 'autogenerated', dirName: 'client-sdks/desktop' }],
            },
          ],
        },
        {
          type: 'category',
          label: 'Sample Apps',
          customProps: {
            icon: '🛝',
          },
          link: { type: 'doc', id: 'sample-apps/sample-apps' },
          items: [{ type: 'autogenerated', dirName: 'sample-apps' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      customProps: {
        icon: '🔌',
      },
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Client Analytics',
          customProps: {
            icon: '📊',
          },
          link: { type: 'doc', id: 'client-analytics/client-analytics' },
          items: [{ type: 'autogenerated', dirName: 'client-analytics' }],
        },
        {
          type: 'category',
          label: 'Hardware Encoders',
          customProps: {
            icon: '🖥️',
          },
          link: { type: 'doc', id: 'hardware-encoders/index' },
          items: [{ type: 'autogenerated', dirName: 'hardware-encoders' }],
        },
        {
          type: 'category',
          label: 'Software Encoders',
          customProps: {
            icon: '💿',
          },
          link: { type: 'doc', id: 'software-encoders/index' },
          items: [{ type: 'autogenerated', dirName: 'software-encoders' }],
        },
        // TODO Port https://docs.dolby.io/streaming-apis/docs/amino
        // {
        //   type: 'category',
        //   label: 'Playback Devices',
        //   customProps: {
        //     icon: '📺',
        //   },
        //   items: ['amino'],
        // },
      ],
    },
  ],
};

export default sidebars;
