import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  theolive: [
    'index',
    'getting-started',
    {
      type: 'category',
      label: 'Contribution',
      customProps: {
        icon: '🚀',
      },
      description: 'THEOLive Contribution/publishing guides',
      link: { type: 'doc', id: 'contribution/stream-configuration' },
      items: [{ type: 'autogenerated', dirName: 'contribution' }],
    },
    {
      type: 'category',
      label: 'Platform',
      customProps: {
        icon: '🚀',
      },
      description: 'THEOLive Platform guides',
      link: { type: 'doc', id: 'platform/manage-team' },
      items: [{ type: 'autogenerated', dirName: 'platform' }],
    },
    {
      type: 'category',
      label: 'Playback',
      customProps: {
        icon: '🚀',
      },
      description: 'THEOLive Playback/Player guides',
      link: { type: 'doc', id: 'playback/Web/getting-started' },
      items: [{ type: 'autogenerated', dirName: 'playback' }],
    },
    'troubleshooting',
    {
      type: 'link',
      label: 'API reference',
      description: 'THEOlive backend API reference',
      customProps: {
        icon: '*️⃣',
      },
      href: 'https://developers.theo.live/reference/create-channel',
    },
  ],
};

export default sidebars;
