import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  theolive: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      customProps: {
        icon: '🚀',
      },
      description: 'Getting started with THEOLive',
      link: { type: 'doc', id: 'getting-started/index' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
  ],
};

export default sidebars;
