import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  web: [
    'web/index',
    { type: 'doc', id: 'external/web-ui/docs/getting-started' },
    {
      type: 'category',
      label: 'How-to guides',
      description: 'Learn how to integrate our rich set of features into your own UI.',
      customProps: {
        icon: '📖',
      },
      link: { type: 'generated-index', slug: 'web/guides' },
      items: [{ type: 'autogenerated', dirName: 'external/web-ui/docs/guides' }],
    },
    {
      type: 'category',
      label: 'Examples',
      description: 'Find inspiration for your UI from our live demos!',
      customProps: {
        icon: '🛝',
      },
      link: { type: 'generated-index', slug: 'web/examples' },
      items: [{ type: 'autogenerated', dirName: 'external/web-ui/docs/examples' }],
    },
    { type: 'doc', id: 'external/web-ui/CHANGELOG' },
    {
      type: 'link',
      label: 'API reference',
      description: 'Discover all components provided by Open Video UI for Web.',
      customProps: {
        icon: '*️⃣',
      },
      href: 'https://theoplayer.github.io/web-ui/api/',
    },
    {
      type: 'link',
      label: 'GitHub',
      description: 'Browse the source code or report issues on GitHub.',
      customProps: {
        icon: 'github',
      },
      href: 'https://github.com/THEOplayer/web-ui/',
    },
  ],
  android: [
    'android/index',
    { type: 'doc', id: 'android/getting-started' },
    {
      type: 'category',
      label: 'How-to guides',
      description: 'Learn how to integrate our rich set of features into your own UI.',
      customProps: {
        icon: '📖',
      },
      link: { type: 'generated-index', slug: 'android/guides' },
      items: [{ type: 'autogenerated', dirName: 'external/android-ui/docs/guides' }],
    },
    { type: 'doc', id: 'external/android-ui/CHANGELOG' },
    {
      type: 'link',
      label: 'API reference',
      description: 'Discover all components provided by Open Video UI for Android.',
      customProps: {
        icon: '*️⃣',
      },
      href: 'https://theoplayer.github.io/android-ui/api/',
    },
    {
      type: 'link',
      label: 'GitHub',
      description: 'Browse the source code or report issues on GitHub.',
      customProps: {
        icon: 'github',
      },
      href: 'https://github.com/THEOplayer/android-ui/',
    },
  ],
  react: [
    'react/index',
    { type: 'doc', id: 'external/web-ui/docs/react/getting-started' },
    {
      type: 'category',
      label: 'How-to guides',
      description: 'Learn how to integrate our rich set of features into your own UI.',
      customProps: {
        icon: '📖',
      },
      link: { type: 'generated-index', slug: 'react/guides' },
      items: [
        // { type: 'autogenerated', dirName: 'external/web-ui/docs/guides' }
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      description: 'Find inspiration for your UI from our live demos!',
      customProps: {
        icon: '🛝',
      },
      link: { type: 'generated-index', slug: 'react/examples' },
      items: [{ type: 'autogenerated', dirName: 'external/web-ui/docs/react/examples' }],
    },
    { type: 'doc', id: 'external/web-ui/react/CHANGELOG' },
    {
      type: 'link',
      label: 'API reference',
      description: 'Discover all components and hooks provided by Open Video UI for React.',
      customProps: {
        icon: '*️⃣',
      },
      href: 'https://theoplayer.github.io/web-ui/react-api/',
    },
    {
      type: 'link',
      label: 'GitHub',
      description: 'Browse the source code or report issues on GitHub.',
      customProps: {
        icon: 'github',
      },
      href: 'https://github.com/THEOplayer/web-ui/tree/main/react/',
    },
  ],
  'react-native': [
    'react-native/index',
    { type: 'autogenerated', dirName: 'external/react-native-theoplayer-ui/doc' },
    { type: 'doc', id: 'external/react-native-theoplayer-ui/CHANGELOG' },
    {
      type: 'link',
      label: 'API reference',
      description: 'Discover all components and functions provided by the React Native UI.',
      customProps: {
        icon: '*️⃣',
      },
      href: 'https://theoplayer.github.io/react-native-theoplayer-ui/api/',
    },
    {
      type: 'link',
      label: 'GitHub',
      description: 'Browse the source code or report issues on GitHub.',
      customProps: {
        icon: 'github',
      },
      href: 'https://github.com/THEOplayer/react-native-theoplayer-ui/',
    },
  ],
};

export default sidebars;
