import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/millicast-api",
    },
    {
      type: "category",
      label: "Analytics",
      items: [
        {
          type: "doc",
          id: "api/analytics-account-total",
          label: "Account Total",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-account-series",
          label: "Account Series",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-account-geo-total",
          label: "Account Geo Total",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-account-geo-series",
          label: "Account Geo Series",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-streams-total",
          label: "Streams Total",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-streams-series",
          label: "Streams Series",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-streams-geo-total",
          label: "Streams Geo Total",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-streams-geo-series",
          label: "Streams Geo Series",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-account-geo",
          label: "Account Geo",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-streams-geo",
          label: "Streams Geo",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-get-tracking-total-for-streams",
          label: "Total bandwidth per TrackingID per stream",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-get-tracking-series-for-streams",
          label: "Series bandwidth per TrackingID per stream",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-get-total-bandwidth-for-tracking-id",
          label: "Total bandwidth for streams specified by TrackingID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-get-series-bandwidth-for-tracking-id",
          label: "Series bandwidth for streams specified by TrackingID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-get-total-transcoder-minutes-for-account",
          label: "Get Total Transcoder Minutes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-get-series-transcoder-minutes-for-account",
          label: "Get Transcoder Minutes Series",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-media-asset-usage",
          label: "Usage",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-media-asset-usage-billable",
          label: "Usage Billable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-get-drm-daily-usage",
          label: "DRM Daily Usage",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/analytics-get-drm-total-usage",
          label: "DRM Total Usage",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Account",
      items: [
        {
          type: "doc",
          id: "api/account-update-expiration-rules",
          label: "Update Account Media Assets Expiration Rules",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/account-get-expiration-rules",
          label: "Get Account Media Assets Expiration Rule",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/account-list-storage-profiles",
          label: "List Storage Profiles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/account-create-storage-profile",
          label: "Create Storage Profile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/account-delete-storage-profile",
          label: "Delete Storage Profile",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/account-get-storage-profile",
          label: "Get Storage Profile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/account-update-storage-profile",
          label: "Update Storage Profile",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/account-validate-third-party-storage",
          label: "Validate Third Party Storage Setup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/account-get-account-distribution",
          label: "Read Account Distribution Settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/account-update-account-distribution",
          label: "Update Account Distribution Settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/account-get-account-security",
          label: "Read Account Security Settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/account-update-account-security",
          label: "Update Account Security Settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/account-get-geo-cascade",
          label: "Read Account Geo Cascade Settings",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/account-update-geo-cascade",
          label: "Update Account Geo Cascade Settings",
          className: "menu__list-item--deprecated api-method put",
        },
        {
          type: "doc",
          id: "api/geo-geo",
          label: "Read Account Geo Restrictions",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/geo-update-geo",
          label: "Update Account Geo Restrictions",
          className: "menu__list-item--deprecated api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "MediaAssets",
      items: [
        {
          type: "doc",
          id: "api/media-assets-create-media-asset",
          label: "Create Media Asset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/media-assets-list-media-assets",
          label: "List Media Assets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/media-assets-delete-media-assets",
          label: "Delete Media Assets",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/media-assets-read-media-asset",
          label: "Read Media Asset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/media-assets-delete-media-assets-2",
          label: "Delete All Media Assets",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Beta",
      items: [
        {
          type: "doc",
          id: "api/record-files-v-2-list-media-assets",
          label: "List Media Assets",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-v-2-read-media-asset",
          label: "Read Media Asset",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-v-2-delete-media-assets",
          label: "Delete Media Assets",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/record-files-create-record-clip",
          label: "Create Clip",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/record-files-get-clip-request",
          label: "Get Clip Request",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-delete-clip-request-live",
          label: "Delete Clip Request",
          className: "menu__list-item--deprecated api-method delete",
        },
        {
          type: "doc",
          id: "api/record-files-list-clip-requests",
          label: "List Clip Requests",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-list-available-clip-sources",
          label: "List Available Clip Sources",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-validate-storage-profile",
          label: "Validate Third Party Storage Setup",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/record-files-update-expiry-rule",
          label: "Update Clip Source Expiry Rule",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/record-files-get-expiry-rule",
          label: "Get Clip Source Expiry Rule",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-delete-expiry-rule",
          label: "Delete Clip Source Expiry Rule",
          className: "menu__list-item--deprecated api-method delete",
        },
        {
          type: "doc",
          id: "api/record-files-delete-clip-sources",
          label: "Delete Clip Sources",
          className: "menu__list-item--deprecated api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "hidden",
      items: [
        {
          type: "doc",
          id: "api/record-files-v-2-list-media-assets",
          label: "List Media Assets",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-v-2-read-media-asset",
          label: "Read Media Asset",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-v-2-delete-media-assets",
          label: "Delete Media Assets",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/record-files-create-record-clip",
          label: "Create Clip",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/record-files-get-clip-request",
          label: "Get Clip Request",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-delete-clip-request-live",
          label: "Delete Clip Request",
          className: "menu__list-item--deprecated api-method delete",
        },
        {
          type: "doc",
          id: "api/record-files-list-clip-requests",
          label: "List Clip Requests",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-list-available-clip-sources",
          label: "List Available Clip Sources",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-validate-storage-profile",
          label: "Validate Third Party Storage Setup",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/record-files-update-expiry-rule",
          label: "Update Clip Source Expiry Rule",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/record-files-get-expiry-rule",
          label: "Get Clip Source Expiry Rule",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-delete-expiry-rule",
          label: "Delete Clip Source Expiry Rule",
          className: "menu__list-item--deprecated api-method delete",
        },
        {
          type: "doc",
          id: "api/record-files-delete-clip-sources",
          label: "Delete Clip Sources",
          className: "menu__list-item--deprecated api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "PublishTokenV2",
      items: [
        {
          type: "doc",
          id: "api/publish-token-v-2-update-token",
          label: "Update Token",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "SubscribeTokenV2",
      items: [
        {
          type: "doc",
          id: "api/subscribe-token-v-2-update-token",
          label: "Update Token",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Monitoring",
      items: [
        {
          type: "doc",
          id: "api/monitoring-list-recent-streams",
          label: "List Streams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/monitoring-get-stream",
          label: "Stream Details",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Transcoder",
      items: [
        {
          type: "doc",
          id: "api/transcoder-get-transcoder",
          label: "Get Transcoder",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/transcoder-update-transcoder",
          label: "Update Transcoder",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/transcoder-delete-transcoder",
          label: "Delete Transcoder",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/transcoder-create-transcoder",
          label: "Create Transcoder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/transcoder-list-transcoders",
          label: "List Transcoders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/transcoder-start-transcoder",
          label: "Start Transcoder",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/transcoder-stop-transcoder",
          label: "Stop Transcoder",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/transcoder-get-transcoder-instance",
          label: "Get Transcoder Instance",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/transcoder-list-transcoder-instances",
          label: "List Transcoder Instances",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/transcoder-list-transcoder-profiles",
          label: "List Transcoder Profiles",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "TranscoderScheduler",
      items: [
        {
          type: "doc",
          id: "api/transcoder-scheduler-create-schedule",
          label: "Create Transcoder Schedule",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/transcoder-scheduler-delete-schedule",
          label: "Delete Transcoder Schedule",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/transcoder-scheduler-update-schedule",
          label: "Update Transcoder Schedule",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/transcoder-scheduler-get-schedule-by-schedule-id",
          label: "Get Transcoder Schedule",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/transcoder-scheduler-list-all-schedules",
          label: "List Transcoder Schedules",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/transcoder-scheduler-get-schedules-for-transcoder",
          label: "Get Schedules By Transcoder",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Cluster",
      items: [
        {
          type: "doc",
          id: "api/cluster-get-clusters-info",
          label: "Read Clusters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/cluster-update-cluster-info",
          label: "Update Cluster",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "PublishTokenV1",
      items: [
        {
          type: "doc",
          id: "api/publish-token-v-1-read-token",
          label: "Read Token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/publish-token-v-1-delete-token",
          label: "Delete Token",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/publish-token-v-1-update-token",
          label: "Update Token",
          className: "menu__list-item--deprecated api-method put",
        },
        {
          type: "doc",
          id: "api/publish-token-v-1-list-tokens",
          label: "List Tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/publish-token-v-1-list-tokens-by-name",
          label: "List Tokens By Name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/publish-token-v-1-list-tokens-by-cluster",
          label: "List Tokens By Cluster",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/publish-token-v-1-create-token",
          label: "Create Token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/publish-token-v-1-get-active-token-by-stream-id",
          label: "Get active Publish Token ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/publish-token-v-1-get-all-active-tokens-by-account",
          label: "Get all active Publish Token IDs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/publish-token-v-1-disable-tokens",
          label: "Disable Publish Token(s)",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "RecordFiles",
      items: [
        {
          type: "doc",
          id: "api/record-files-get-record-file",
          label: "Read File",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-delete-record-file",
          label: "Delete File",
          className: "menu__list-item--deprecated api-method delete",
        },
        {
          type: "doc",
          id: "api/record-files-delete-record-files",
          label: "Delete Files",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/record-files-delete-all-record-files",
          label: "Delete All Files",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/record-files-list-record-files",
          label: "List Files",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-list-record-files-by-token",
          label: "List Files By Token",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-list-record-files-by-stream",
          label: "List Files By Stream",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-record-file-usage",
          label: "Usage",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/record-files-record-file-usage-billable",
          label: "Usage Billable",
          className: "menu__list-item--deprecated api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Stream",
      items: [
        {
          type: "doc",
          id: "api/stream-stop-stream",
          label: "Stop an active stream",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/stream-stop-by-account",
          label: "Stop all active streams",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/stream-reprioritize-stream",
          label: "Reprioritize an active stream",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "SubscribeTokenV1",
      items: [
        {
          type: "doc",
          id: "api/subscribe-token-v-1-read-token",
          label: "Read Token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/subscribe-token-v-1-delete-token",
          label: "Delete Token",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/subscribe-token-v-1-update-token",
          label: "Update Token",
          className: "menu__list-item--deprecated api-method put",
        },
        {
          type: "doc",
          id: "api/subscribe-token-v-1-list-tokens",
          label: "List Tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/subscribe-token-v-1-list-tokens-by-name",
          label: "List Tokens By Name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/subscribe-token-v-1-create-token",
          label: "Create Token",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Webhooks",
      items: [
        {
          type: "doc",
          id: "api/webhooks-get",
          label: "Read Webhook",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/webhooks-update-webhook",
          label: "Update Webhook",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/webhooks-remove-webhook",
          label: "Remove Webhook",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/webhooks-list-webhooks",
          label: "List Webhooks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/webhooks-add-webhook",
          label: "Add Webhook",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/webhooks-test-webhook",
          label: "Test Webhook",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
