name: Deploy website

on:
  workflow_call:
    inputs:
      environment_name:
        type: string
        required: true
      environment_url:
        description: |
          The URL where the website will be deployed.
          This will be shown on the deployment page and on the triggering pull request.
        type: string
        required: false
        default: ''
      artifact_name:
        description: Name of the built artifact for deployment.
        required: true
        type: string
      s3_prefix:
        description: AWS S3 prefix where to store the build.
        required: true
        type: string
      cf_invalidate_path:
        description: Path to invalidate on CloudFront after deployment.
        required: true
        type: string

concurrency: deploy-${{ github.ref }}

jobs:
  deploy-to-cloudfront:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment_name }}
      deployment: true
      url: ${{ inputs.environment_url }}
    permissions:
      id-token: write
      pull-requests: write
    steps:
      - name: Create app token
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.THEOPLAYER_BOT_APP_ID }}
          private-key: ${{ secrets.THEOPLAYER_BOT_PRIVATE_KEY }}

      - name: Download build artifact 🗃️
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ github.workspace }}/${{ inputs.artifact_name }}

      - name: Configure AWS credentials ☁️
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE }}

      - name: 'Sync to ${{ inputs.s3_prefix }} on S3 💾'
        run: |
          echo "Copying artifact: ${ARTIFACT_PATH} to S3 bucket: ${S3_BUCKET}/${S3_PREFIX}"
          aws s3 sync ${ARTIFACT_PATH}/ s3://${S3_BUCKET}/${S3_PREFIX}/ \
            --only-show-errors \
            --delete
        env:
          S3_BUCKET: ${{ vars.S3_BUCKET_NAME }}
          S3_PREFIX: ${{ inputs.s3_prefix }}
          ARTIFACT_PATH: ${{ github.workspace }}/${{ inputs.artifact_name }}

      - name: Invalidate Amazon CloudFront 🧹
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${CF_DISTRIBUTION_ID} \
            --paths "${PATH_TO_INVALIDATE}"
        env:
          CF_DISTRIBUTION_ID: ${{ vars.CF_DISTRIBUTION_ID }}
          PATH_TO_INVALIDATE: ${{ inputs.cf_invalidate_path }}

      - name: Get deployment timestamp 🕰️
        id: timestamp
        if: ${{ inputs.environment_name == 'preview' }}
        run: echo "time=$(date -u '+%Y-%m-%d %H:%M %Z')" >> "$GITHUB_OUTPUT"

      - name: Add comment to Pull Request with link to preview 🕸️
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ inputs.environment_name == 'preview' }}
        with:
          header: pr-preview
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          message: |
            Documentation preview
            :---:
            | :rocket: View preview at <br> ${{ inputs.environment_url }} <br><br>
            | <h6>Deployed from commit ${{ github.event.pull_request.head.sha }} at ${{ steps.timestamp.outputs.time }}.</h6>
