name: Deploy to staging
on:
  workflow_dispatch:
concurrency:
  group: staging
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    # Permissions needed to interact with GitHub's OIDC Token endpoint
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true
      # Build the website
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run build
        env:
          THEOPLAYER_LICENSE: ${{ vars.THEOPLAYER_LICENSE }}
          DOCUSAURUS_BASE_URL: /docs/
      # Deploy to S3
      # See https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::823129359776:role/optiview-docs-github
          aws-region: us-west-2
      - name: Deploy to S3
        run: |
          aws s3 sync --delete ./build s3://docs-staging-optiview-dolby-com-0-20250610142618642800000001/
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id E15SU691K20UEP --paths '/*'
