name: Lint
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Create Ads OpenAPI token
        uses: actions/create-github-app-token@v3
        id: ads-token
        with:
          client-id: ${{ vars.THEOPLAYER_BOT_CLIENT_ID }}
          private-key: ${{ secrets.THEOPLAYER_BOT_PRIVATE_KEY }}
          owner: Dolby-OptiView
          repositories: optiview-ads
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          submodules: true
      - name: Use Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run gen-api-docs
        env:
          GITHUB_TOKEN: ${{ steps.ads-token.outputs.token }}
      - run: npm run check-format
      - run: npm run lint
      - run: npm run typecheck
